# Generated by Django 5.1.5 on 2025-01-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeManager', '0002_areasmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasmodel',
            name='milestones',
            field=models.JSONField(),
        ),
    ]
