# Generated by Django 5.1.5 on 2025-01-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifeManager', '0006_subtasksmodel_tasksmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtasksmodel',
            old_name='task',
            new_name='subtask',
        ),
    ]
